### ISSUE TITLE
Failed to activate the atom-react-native-autocomplete package

### ISSUE THREAD

**Issue by wangujianchi** [TOP-Chao/atom-react-native-autocomplete#11]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.3 ia32
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [atom-react-native-autocomplete](https://github.com/TOP-Chao/atom-react-native-autocomplete) package 0.0.27

### Stack Trace

Failed to activate the atom-react-native-autocomplete package

```
At Cannot find module 'atom-package-deps'

Error: Cannot find module 'atom-package-deps'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.14.3/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.activate (/packages/atom-react-native-autocomplete-master/lib/autocomplete.js:30:9)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:814:28
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-modules 1.6.7 
atom-beautify 0.29.13 
atom-react-autocomplete 0.1.10 
react-es6-snippets 0.3.0 
atom-react-native-autocomplete 0.0.27 
atom-react-native-autocomplete 0.0.27 
react-snippets 0.7.0 
atom-ternjs 0.16.1 
autocomplete-js-import 1.4.0 
color-picker 2.2.3 
emmet 2.4.3 
emmet-jsx-css-modules 1.0.0 
file-icons 1.7.25 
language-babel 2.55.4 
language-javascript-jsx 0.3.7 
Stylus 3.0.0 
language-vue 0.21.0 
markdown-writer 2.6.2 
minimap 4.26.4 
node-debugger 1.9.1 
pigments 0.38.0 
platformio-ide-terminal 2.2.2 
script 3.12.2 
simplified-chinese-menu 3.5.0 
split-diff 1.1.0 
Stylus 3.0.0 
terminal-panel 1.14.1 
terminal-plus 0.14.5 
```

**Comment by TOP-Chao** [comment]
I'm sorry, the project has stopped maintenance.
